[bttc]
src.github = "bttcprotocol/bttc"
fetch.github = "bttcprotocol/bttc"
git.fetchSubmodules = true

[delivery]
src.github = "bttcprotocol/delivery"
fetch.github = "bttcprotocol/delivery"
git.fetchSubmodules = true

[launch]
src.git = "https://github.com/bttcprotocol/launch.git"
#src.manual = "f71388e3a8091a1c6bc10aa03d7edf8e7b638f23"
fetch.git = "https://github.com/bttcprotocol/launch.git"

[my_cookies]
src.pypi="my_cookies"
fetch.pypi="my_cookies"

#zsh plugins
[alias-tips]
src.git = "https://github.com/djui/alias-tips.git"
fetch.git = "https://github.com/djui/alias-tips.git"

[wakatime-zsh-plugin]
src.git = "https://github.com/sobolevn/wakatime-zsh-plugin.git"
fetch.git = "https://github.com/sobolevn/wakatime-zsh-plugin.git"

[forgit]
src.git = "https://github.com/wfxr/forgit.git"
fetch.git = "https://github.com/wfxr/forgit.git"

[epc]
src.pypi="epc"
fetch.pypi="epc"
