# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
    author-name: xiongchenyu
    author-email: chenyu.xiong@bitmain.com
    copyright: None
    github-username: xiongchenyu6

extra-include-dirs: 
- /home/chenyu/.wire-dev/include
extra-lib-dirs:
- /home/chenyu/.wire-dev/lib


#nix:
  #enable: true
