extra-lib-dirs:
- /home/chenyu/.wire-dev/lib
extra-include-dirs:
- /home/chenyu/.wire-dev/include
system-ghc: true
templates:
  params:
    author-name: xiongchenyu
    author-email: chenyu.xiong@bitmain.com
    github-username: xiongchenyu6
    copyright: None
