
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$all"""
# A continuation prompt that displays two filled in arrows
continuation_prompt = "▶▶"

[kubernetes]
disabled = false
[directory]
truncation_length = 8
truncation_symbol = "…/"
[status]
disabled = false
[time]
disabled = false
[git_commit]
tag_disabled = false
[git_metrics]
disabled = false
[python]
disabled = false
[sudo]
disabled = false
